name: Ruby

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: bundle install
      shell: bash
      run:  |
        docker compose up tdd -d
        docker compose exec tdd bundle install
    - name: Run Rubocop
      shell: bash
      run:  |
        docker compose exec tdd bundle exec rubocop --parallel
    - name: Run tests for minitest
      shell: bash
      run:  |
        docker compose exec tdd rake test
    - name: Run tests for RSpec
      shell: bash
      run:  |
        docker compose exec tdd bundle exec rspec
      env:
        RACK_ENV: test
